//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ead_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_info
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> wed_date { get; set; }
        public Nullable<System.TimeSpan> wed_time { get; set; }
        public string city { get; set; }
    }
}
