//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ead_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeddingEntities14 : DbContext
    {
        public WeddingEntities14()
            : base("name=WeddingEntities14")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin_login> admin_login { get; set; }
        public DbSet<check_info> check_info { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Register> Registers { get; set; }
        public DbSet<Registeration> Registerations { get; set; }
        public DbSet<Signup> Signups { get; set; }
        public DbSet<Theme> Themes { get; set; }
    }
}
