//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ead_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registeration
    {
        public int Id { get; set; }
        public string email { get; set; }
        public Nullable<int> cnic { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string p_address { get; set; }
        public string t_address { get; set; }
        public string theme_name { get; set; }
        public string color_combination { get; set; }
        public string seating_arrangement { get; set; }
        public string stage_arrangemenet { get; set; }
        public string stage_lightening { get; set; }
        public Nullable<int> budget { get; set; }
    }
}
