//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ead_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public string theme_name { get; set; }
        public string color_combination { get; set; }
        public string seating_arrangnment { get; set; }
        public string stage_arrangnment { get; set; }
        public string stage_seating { get; set; }
        public string stage_lightening { get; set; }
        public Nullable<int> budget { get; set; }
        public int Theme_id { get; set; }
    }
}
